### ISSUE TITLE
How to use without unity

### ISSUE THREAD

**Issue by eiredrake** [lezhkin11/mvvm-wizard#1]
Not really an issue per se. I might just be trying to use your framework in an way it wasn't intended. Been having a heck of a time using the framework. Turns out I wasn't registering with Unity. Once I did that my views resolved themselves automagically. However I really don't want to have to retool my entire DI scheme. 

I went so far as to start a wPF test harness and directly copy and paste your views and still got the example object reference error. The line that things were crashing on was line 412 in the Wizard.cs file. 

`            WizardStep stepToSelect = (WizardStep)this.Items[transitToIndex];

            if (stepToSelect.Content == null && stepToSelect.ViewType != null)
            {
                stepToSelect.Content = WizardSettings.Instance.ViewResolver(stepToSelect.ViewType);
            }`

What seems to be happening is that my wizard step, which is setup in XAML on my mainwindow

`            <controls:WizardStep ViewType="{x:Type views:WelcomeView}"/>`

This is a copy/paste of your WelcomeView in the demo. It doesn't' actually do anything. So long as I call resolve on the UnityContainer the stepToSelect.Content is populated. I don't really understand this since the content of the welcome view should be already populated by the fact that there's a view file full of components right?

            var unityContainer = new UnityContainer();
            WizardSettings.Instance.ViewResolver = type => unityContainer.Resolve(type);

Is there a way to populate that just with the view itself or xaml? I am already using a dependency injection system that I don't want to have to replace. I tried using the Content="" attribute on the wizard step but it wouldn't accept anything I put in there. Since the code is checking to see if teh Content is populated before it calls the viewresolver... I assume there must be a way to do it..otherwise it wouldn't need that conditional.

Any advice?

**Comment by lezhkin11** [comment]
Which DI do yo use? it's not necessary to use unity. You can even use reflection to resolve things. Pretty sure it's easy to adapt to many DI containers.
Set `WizardSettings.Instance.ViewResolver` in bootstrapper, where you have access to your DI container.

```
WizardSettings.Instance.ViewResolver = type => YOUR_CONTAINER.Resolve(type);
```

> I don't really understand this since the content of the welcome view should be already populated by the fact that there's a view file

`<controls:WizardStep ViewType="{x:Type views:WelcomeView}"/>` - this bit doesn't create view and all underlying controls.  You only specify type  here. View itself will be created on demand (by  navigating to step first time)

You also can set `Content` directly to each step. Setting `Content` directly has the highest priority, so `ViewType` will be ignored:

```
<controls:WizardStep BackButtonVisibility="Collapsed">
     <controls:WizardStep.Content>
         <!-- Your controls/view here. -->
         <TextBlock Text="HELLO" />
    </controls:WizardStep.Content>
</controls:WizardStep>
```
