### ISSUE TITLE
Async vs Non-Async Methods

### ISSUE THREAD

**Issue by mysteryx93** [lezhkin11/mvvm-wizard#2]
This is not respecting coding standards

    public override async Task OnTransitedFrom(TransitionContext transitionContext)

An Async method should end with Async.

I think it would be best to have 2 methods to override, one with Async and one without.

That's exactly what ASP.NET does with OnGet/OnGetAsync, where we can implement either one.

I think it would also be useful to add these methods on transitionContext to know which command was executed: IsNextStepCommand, IsPreviousStepCommand, IsSkipCommand, IsFinishCommand

**Comment by mysteryx93** [comment]
Thinking of it, I don't see the reason for an async method here -- if you need to do async work in there, you can make it async void, but the navigation action can't continue until it knows what to do so I think async work should be avoided here.

Then transitionContext could have an Action property that returns an enum with the executed action. This would greatly simplify the code checking whether it's an action forward or backwards.

**Comment by lezhkin11** [comment]
With non-aysnc method the next step will be displayed straightaway. Current desired behaviour waits until current step is fully completed then wizard displays/creates next step. You can achieve similar without async methods, but it will be a "bicycle" with 5 wheels + usage won't be intuitive and simple.

Regarding `IsNextStepCommand, IsPreviousStepCommand, IsSkipCommand, IsFinishCommand`:
Finish command is a standalone and not part of transitioning process, so user always know that this was executed by FinishCommand
Skip command - there is a property `TransitionContext -> IsSkipAction`
So, all you need to know whether it's `NextStep` or `PreviousStep`, which you can easily identify by `TransitionContext.TransitToStep - TransitionContext.TransitedFromStep`
