### ISSUE TITLE
Howto pass data into the wizard and howto retrieve data from it

### ISSUE THREAD

**Issue by sa-he** [lezhkin11/mvvm-wizard#3]
Inspired by e.g. the classic OpenFileDialog I'm looking for the following usage.

```
var wizard = new MyWizard()
wizard.MySetting = 88; // predefine some value
wizard.ShowDialog();
var result = wizard.MySetting; // get value that have been modified or confirmed by the user
```

I was thinking if it might be good to make 
`private readonly Dictionary<string, object> sharedContext;` in Wizard.cs public? Then I could:

```
var wizard = new MyWizard()
wizard.SharedContext["MySetting"] = 88; // predefine some value
wizard.ShowDialog();
var result = wizard.SharedContext["MySetting"]; // get value that have been modified or confirmed by the user
```

**Comment by lezhkin11** [comment]
Wizard now has public dependency property. More details here https://github.com/lezhkin11/mvvm-wizard/wiki/Pass-Data-to-from-Wizard

Available at version **1.1.1**
