### ISSUE TITLE
Customize summary item

### ISSUE THREAD

**Issue by chrno1209** [lezhkin11/mvvm-wizard#4]
Thank you for great Wpf control, I am now using it for my project, but my customer wants to customize the summary item which contain text to describe the current step instead of just an colored ellipse.
Can you point me out on how to do that?
Many thanks.

**Comment by lezhkin11** [comment]
Check this out https://github.com/lezhkin11/mvvm-wizard/wiki/Custom-Template-for-Summary-Item
