### ISSUE TITLE
How can I set TransitionController.NextStepCommand CanExecute from a StepViewModel 

### ISSUE THREAD

**Issue by mansofta** [lezhkin11/mvvm-wizard#6]

**Comment by mansofta** [comment]
Some of my StepViewModels need to validate data before user can click on Next button

**Comment by mansofta** [comment]
Some of my StepViewModels need to validate data before user can click on Next button

**Comment by lezhkin11** [comment]
you can bind `ForwardButtonIsEnabled` to your viewModel via `UnderlyingDataContext` of the `WizardStep` control.
`UnderlyingDataContext` holds your viewmodel.
For example:
```
<controls:WizardStep 
         x:Name="RegistrationStep" 
         ViewType="{x:Type simple:RegistrationView}"  
         ForwardButtonIsEnabled="{Binding UnderlyingDataContext.MyIsEnabled, RelativeSource={RelativeSource Self}}"/>
```

See commit https://github.com/lezhkin11/mvvm-wizard/commit/6667b4cff85377bd4c417370b71e912ef2afb4c3
Also, wiki https://github.com/lezhkin11/mvvm-wizard/wiki/Bind-ViewModel-to-WizardStep-Control
