### ISSUE TITLE
Styling Controls like Next and Skip

### ISSUE THREAD

**Issue by saadsaeed01** [lezhkin11/mvvm-wizard#9]
Hello 

Can you please tell me that what is the way of styling controls?

![image](https://user-images.githubusercontent.com/33133831/151950242-5b546a7f-8cbc-4bae-97ae-466de81155c6.png)

**Comment by lezhkin11** [comment]
Hi,
for summary items there are some basic properties (different brushes, width, height and etc.) If you need more control, then you need to override default templates
For example, how to set custom style for WizardStep
https://github.com/lezhkin11/mvvm-wizard/wiki/Custom-Template-for-Summary-Item

Navigation buttons can be controlled by `BackButtonStyle`, `SkipButtonStyle`, `ForwardButtonStyle` (at Wizard level control)
https://github.com/lezhkin11/mvvm-wizard/blob/master/src/MvvmWizard/Controls/Wizard.TransitionButtons.cs

**Comment by saadsaeed01** [comment]
> Hi, You need to override default templates For example, how to set custom style for WizardStep https://github.com/lezhkin11/mvvm-wizard/wiki/Custom-Template-for-Summary-Item
> 
> Navigation buttons can be controlled by `BackButtonStyle`, `SkipButtonStyle`, `ForwardButtonStyle` (at Wizard level control) https://github.com/lezhkin11/mvvm-wizard/blob/master/src/MvvmWizard/Controls/Wizard.TransitionButtons.cs

Got it many thanks!
